import opuesto from "./opuesto";

const baseline = [
	{ es: "Mi papá ama las papas.", en: "My dad loves potatoes." },
	{ es: "¿nos vamos?", en: "Are we going?" },
	{ es: "¿Eres un hijo de Dios?", en: "Are you a child of God?" },
	{ es: "¿Vas a ir?", en: "Are you going?" },
	{ es: "¿Vas a comer?", en: "Are you going to eat?" },
	{ es: "¿Estás jubilado?", en: "Are you retired?" },
	{ es: "¿Eres el pastor?", en: "Are you the pastor?" },
	{ es: "¡Adiós! ¡Gracias por todo!", en: "Bye! Thanks for everything!" },
	{ es: "¿Puedo orar por ti?", en: "Can I pray for you?" },
	{ es: "¿Puedes hablar inglés?", en: "Can you speak English?" },
	{ es: "¿Puedes hablar más despacio?", en: "Can you speak slower?" },
	{ es: "¿Tienes una biblia?", en: "Do you have a bible?" },
	{ es: "¿Usted tiene un coche?", en: "Do you have a car?" },
	{ es: "¿Tienes un bolígrafo?", en: "Do you have a pen?" },
	{ es: "¿Hijos Tienes?", en: "Do you have children?" },
	{ es: "¿Conoces a Jesus?", en: "Do you know Jesus?" },
	{ es: "¿Te gusta leer?", en: "Do you like to read?" },
	{ es: "¿Vives en Cuba?", en: "Do you live in Cuba?" },
	{ es: "¿Vives con tu mamá?", en: "Do you live with your mom?" },
	{ es: "¿Necesitas una biblia?", en: "Do you need a bible?" },
	{ es: "¿Necesitas más para comer?", en: "Do you need more to eat?" },
	{ es: "¿Necesitas decidir?", en: "Do you need to decide?" },
	{ es: "¿Necesitas comer?", en: "Do you need to eat?" },
	{ es: "¿Necesitas ir?", en: "Do you need to go?" },
	{ es: "¿Necesitas irte?", en: "Do you need to leave?" },
	{ es: "¿Practicas español?", en: "Do you practice Spanish?" },
	{ es: "¿Estudias?", en: "Do you study?" },
	{ es: "¿Quieres a Jesús como tu salvador?", en: "Do you want Jesus as your savior?" },
	{ es: "¿Trabajas?", en: "Do you work?" },
	{ es: "Todas las personas necesitan a Jesús.", en: "Every person needs Jesus." },
	{ es: "Todos son muy amables.", en: "Everyone is very kind." },
	{ es: "Perdóneme.", en: "Excuse me." },
	{ es: "Disculpe señor.", en: "Excuse me, Sir." },
	{ es: "¡Gloria a Dios!", en: "Glory to God!" },
	{ es: "Dios siempre es bueno.", en: "God is always good." },
	{ es: "Dios es rey sobre toda la creación.", en: "God is King over all creation." },
	{ es: "Dios es mi padre.", en: "God is my father." },
	{ es: "¡Dios es poderoso!", en: "God is powerful!" },
	{ es: "Dios habla a sus hijos.", en: "God talks to his children." },
	{ es: "¡Buenas noches!", en: "Good evening!" },
	{ es: "¡Buenos dias! Como estas?", en: "Good morning! How are you?" },
	{ es: "¡Genial! ¡Eso es bueno!", en: "Great! That’s good!" },
	{ es: "¡Feliz cumpleaños!", en: "Happy Birthday!" },
	{ es: "El es mi hermano en Cristo.", en: "He is my brother in Christ." },
	{ es: "El es mi amigo.", en: "He is my friend." },
	{ es: "Él está hablando con Mike.", en: "He is talking to Mike." },
	{ es: "Su nombre es Juan.", en: "His name is Juan." },
	{ es: "¿Cómo estás?", en: "How are you?" },
	{ es: "¡Que horrible!", en: "How horrible!" },
	{ es: "¿Cuantos años tienes?", en: "How old are you?" },
	{ es: "Voy a comer.", en: "I will eat." },
	{ es: "Voy a vivir con Jesús por siempre.", en: "I am going to live with Jesus forever." },
	{ es: "Voy a practicar Español", en: "I am going to practice Spanish." },
	{ es: "Voy a leer ahora.", en: "I am going to read now." },
	{ es: "Voy a hablar con el dueño.", en: "I am going to talk to the owner." },
	{ es: "No voy al café", en: "I am not going to the café." },
	{ es: "No voy.", en: "I am not going." },
	{ es: "No cantaré sin él.", en: "I will not sing without him." },
	{ es: "Estoy cantando hoy.", en: "I am singing today." },
	{ es: "soy tu amigo.", en: "I am your friend." },
	{ es: "Yo hablo inglés.", en: "I speak English." },
	{ es: "No como queso.", en: "I do not eat cheese." },
	{ es: "Yo no como pescado vivo.", en: "I do not eat live fish." },
	{ es: "No tengo una pluma.", en: "I do not have a pen." },
	{ es: "No tengo hijos.", en: "I do not have children." },
	{ es: "No me gusta ir al hospital.", en: "I do not like to go to the hospital." },
	{ es: "No necesito más comida.", en: "I do not need more food." },
	{ es: "No necesito hacerlo.", en: "I do not need to do it." },
	{ es: "No canto bien.", en: "I do not sing well." },
	{ es: "No entiendo.", en: "I do not understand." },
	{ es: "No quiero comer.", en: "I do not want to eat." },
	{ es: "Tengo hijos.", en: "I have children." },
	{ es: "Tengo dos bicicletas.", en: "I have two bicycles." },
	{ es: "Tengo dos amigos aquí.", en: "I have two friends here." },
	{ es: "me gusta el queso.", en: "I like cheese." },
	{ es: "Me gusta es, gracias.", en: "I like it, thank you." },
	{ es: "Me gusta el chihuahua.", en: "I like the chihuahua." },
	{ es: "Me gusta beber agua.", en: "I like to drink water." },
	{ es: "Me gusta comer pizza.", en: "I like to eat pizza." },
	{ es: "Me gusta comer.  Te gusta comer?", en: "I like to eat. Do you like to eat?" },
	{ es: "Me gusta alabar a Dios.", en: "I like to praise God." },
	{ es: "Me gusta leer la biblia.", en: "I like to read the bible." },
	{ es: "Vivo en la casa roja.", en: "I live in the red house." },
	{ es: "Amo el chocolate.", en: "I love chocolate." },
	{ es: "Me encanta cantar en la iglesia.", en: "I love to sing in church." },
	{ es: "Necesito una biblia.", en: "I need a bible." },
	{ es: "Necesito una silla.", en: "I need a chair." },
	{ es: "Necesito un poco.", en: "I need a little." },
	{ es: "Necesito una papa.", en: "I need a potato." },
	{ es: "Necesito ayuda, por favor.", en: "I need help, please." },
	{ es: "Necesito un poco más, por favor.", en: "I need a little more, please." },
	{ es: "Necesito decidir.", en: "I need to decide." },
	{ es: "Necesito comer.", en: "I need to eat." },
	{ es: "Necesito irme por la mañana.", en: "I need to leave in the morning." },
	{ es: "Necesito ir a Cuba.", en: "I need to go to Cuba." },
	{ es: "Necesito ir al baño.", en: "I need to go to the bathroom." },
	{ es: "Necesito pagar.", en: "I need to pay." },
	{ es: "Hablo un poco de español.", en: "I speak a little Spanish." },
	{ es: "Quiero beber agua.", en: "I want to drink water." },
	{ es: "Quiero ir a Cuba con ellos.", en: "I want to go to Cuba with them." },
	{ es: "Quiero hablar.", en: "I want to talk." },
	{ es: "Quiero hablarte de Jesús.", en: "I want to talk to you about Jesus." },
	{ es: "Yo creo en Dios.", en: "I believe in God." },
	{ es: "Me gustaría eso.", en: "I would like that." },
	{ es: "Me gustaría cantar.", en: "I would like to sing." },
	{ es: "Quisiera dos, por favor.", en: "I would like two, please." },
	{ es: "No me gustaría ir.", en: "I would not like to go." },
	{ es: "¿Es Dios tu padre?", en: "Is God your father?" },
	{ es: "¿El va?", en: "Is he going?" },
	{ es: "¿Él es tu hermano?", en: "Is he your brother?" },
	{ es: "¿Es su casa?", en: "Is that his house?" },
	{ es: "¿Es el niño tu hijo?", en: "Is the boy your son?" },
	{ es: "¿Es el chihuahua un niño?", en: "Is the chihuahua a boy?" },
	{ es: "Es una buena idea.", en: "It is a good idea." },
	{ es: "Es un placer conocerte.", en: "It’s good to meet you." },
	{ es: "Jesús es Dios.", en: "Jesus is God." },
	{ es: "¡Jesús es Rey!", en: "Jesus is King!" },
	{ es: "Jesús es mi roca.", en: "Jesus is my rock." },
	{ es: "Jesús es nuestra única esperanza.", en: "Jesus is our only hope." },
	{ es: "Jesús es el único salvador.", en: "Jesus is the only savior." },
	{ es: "Jesús es el hijo de Dios.", en: "Jesus is the son of God." },
	{ es: "Jesús vive en mí.", en: "Jesus lives in me." },
	{ es: "Jesús ama a todos.", en: "Jesus loves everyone." },
	{ es: "Jesús te ama.", en: "Jesus loves you." },
	{ es: "¡Comamos!", en: "Let’s eat!" },
	{ es: "Mi madre es muy hermosa.", en: "My mother is very pretty." },
	{ es: 'No, gracias. Como se dice "pollo"?', en: 'No, thank you. How do you say "chicken"?' },
	{ es: "Por favor dime.", en: "Please tell me." },
	{ es: "Orar a Dios es importante.", en: "Praying to God is important." },
	{ es: "Orar es hablar a Dios.", en: "Praying is talking to God." },
	{ es: "Dilo otra vez, por favor.", en: "Say that again, please." },
	{ es: "Hasta luego.", en: "See you later." },
	{ es: "Ella es mi hermana en Cristo.", en: "She is my sister in Christ." },
	{ es: "Cantar a Dios es importante.", en: "Singing to God is important." },
	{ es: "Gracias por todo.", en: "Thank you for everything." },
	{ es: "Gracias por cantar.", en: "Thank you for singing." },
	{ es: "Gracias por estudiar conmigo.", en: "Thank you for studying with me." },
	{ es: "¡Muy gracias!", en: "Thank you so much!" },
	{ es: "Gracias, estoy bien.", en: "Thank you, I am fine." },
	{ es: "Eso es malo. Lo siento.", en: "That’s bad. I am sorry." },
	{ es: "¡Eso es tan bueno!", en: "That’s so good!" },
	{ es: "La Biblia dice que Jesús es el Señor.", en: "The bible says Jesus is Lord." },
	{ es: "El coche es blanco.", en: "The car is white." },
	{ es: "El gato es muy blanco.", en: "The cat is very white." },
	{ es: "El queso es de Chihuahua.", en: "The cheese is from Chihuahua." },
	{ es: "El chihuahua es muy blanco.", en: "The chihuahua is very white" },
	{ es: "¿La niña es tu hija?", en: "The girl is your daughter?" },
	{ es: "Él está con el pastor.", en: "He is with the pastor." },
	{ es: "¡Muy bien!", en: "Very good!" },
	{ es: "Somos hijos de Dios por medio de Cristo.", en: "We are children of God through Christ." },
	{ es: "Somos de Estados Unidos.", en: "We are from the United States." },
	{ es: "Vamos a la iglesia.", en: "We are going to church." },
	{ es: "Vamos a comer en la iglesia.", en: "We are going to eat at church." },
	{ es: "Vamos a rezar.", en: "We are going to pray." },
	{ es: "Vamos a cantar en la iglesia.", en: "We are going to sing at church." },
	{ es: "Vamos a estudiar más tarde.", en: "We are going to study later." },
	{ es: "Nos vamos mañana.", en: "We are going tomorrow." },
	{ es: "Somos justificados por la fe.", en: "We are justified by faith." },
	{ es: "No vamos.", en: "We are not going." },
	{ es: "Vivimos por la fe.", en: "We live by faith." },
	{ es: "Nosotros vivimos en los Estados Unidos.", en: "We live in the United States." },
	{ es: "Necesitamos a Dios.", en: "We need God." },
	{ es: "Necesitamos orar todos los días.", en: "We need to pray every day." },
	{ es: "Necesitamos hablar.", en: "We need to talk." },
	{ es: "¿Qué te gusta?", en: "What do you like?" },
	{ es: "Qué significa eso?", en: "What does that mean?" },
	{ es: "¿Cuál es su nombre?", en: "What is your name?" },
	{ es: "¿Que hora es?", en: "What time is it?" },
	{ es: "¿Cuándo vamos a la iglesia?", en: "When are we going to church?" },
	{ es: "¿Donde estamos comiendo?", en: "Where are we eating?" },
	{ es: "¿Dónde vives?", en: "Where do you live?" },
	{ es: "¿Dónde está ella?", en: "Where is she?" },
	{ es: "¿A dónde él va?", en: "Where is he going?" },
	{ es: "¿Dónde está el baño?", en: "Where is the bathroom?" },
	{ es: "¿Dónde está el niño?", en: "Where is the boy?" },
	{ es: "¿A dónde va el chihuahua?", en: "Where is the chihuahua going?" },
	{ es: "¿Donde esta el chihuahua?", en: "Where is the chihuahua?" },
	{ es: "¿Donde está el pastor?", en: "Where is the pastor?" },
	{ es: "Con Cristo, soy fuerte.", en: "With Christ, I am strong." },
	{ es: "Quiero.", en: "I want." },
	{ es: "Si yo quiero.", en: "Yes I want to." },
	{ es: "Si, gracias.", en: "Yes, thank you." },
	{ es: "Sí, tienes que ir conmigo.", en: "Yes, you need to go with me." },
	{ es: "Lo hiciste muy bien.", en: "You did very well." },
	{ es: "Tu madre canta bien.", en: "Your mom sings well." },
	{ es: "te gusta tu comida?", en: "do you like your food?" },
	{
		es: "Dime con quién andas y te diré quién eres.",
		en: "Tell me who your friends are and I will tell you who you are."
	},
	{ es: "¿cuál es la diferencia?", en: "what is the difference?" }
];

let sentences = baseline.concat(opuesto);

export = sentences;
