export = [
	{ es: "uno", en: "one" },
	{ es: "dos", en: "two" },
	{ es: "tres", en: "three" },
	{ es: "quatro", en: "four" },
	{ es: "cinco", en: "five" },
	{ es: "seis", en: "six" },
	{ es: "siete", en: "seven" },
	{ es: "ocho", en: "eight" },
	{ es: "nueve", en: "nine" },
	{ es: "diez", en: "ten" },
	{ es: "once", en: "eleven" },
	{ es: "doce", en: "twelve" },
	{ es: "trece", en: "thirteen" },
	{ es: "catorce", en: "fourteen" },
	{ es: "quince", en: "fifteen" },
	{ es: "dieciséis", en: "sixteen" },
	{ es: "de diecisiete", en: "seventeen" },
	{ es: "dieciocho", en: "eighteen" },
	{ es: "diecinueve", en: "nineteen" },
	{ es: "veinte", en: "twenty" }
].map(v => ({ a: v.es, q: v.en }));
