export =[
	{ a: "¿Quién eres tú?", q: "who are you?" },
	{ a: "¿Qué eres?", q: "what are you?" },
	{ a: "¿Dónde estás?", q: "Where are you?" },
	{ a: "¿Cuándo corres?", q: "When will you run?" },
	{ a: "¿Por qué caminas?", q: "Why do you walk?" },
	{ a: "¿Con o sin?", q: "With or without?" },
	{ a: "Cuándo?", q: "When?" },
	{ a: "Lunes o Martes?", q: "Monday or Tuesday?" },
	{ a: "Miércoles o Jueves?", q: "Wednesday or Thursday?" },
	{ a: "Viernes y Sábado o Domingo", q: "Friday and Saturday or Sunday" },
	{ a: "¿El partido es mañana?", q: "The match is tomorrow?" },
	{ a: "¿quieres jugar un juego?", q: "do you want to play a game?" },
	{ a: "¿Cual arbol?", q: "Which tree?" },
	{ a: "¿Las ramas más bajas del árbol?", q: "The lowest branches of the tree?" },
	{ a: "¿Donde esta la sierra?", q: "Where is the saw?" },
];
