// from http://www.geonames.org/servlet/geonames?&srv=2&lat=34.866&lng=-82.32&north=34.88201974655184&east=-82.28824264526367&south=34.849977132141696&west=-82.35175735473632&maxRows=100&type=json&q=&P=1&A=1&V=1&T=1&L=1&R=1&S=1&H=1&U=1
export = [{
    "centerPt": {
        "country": "",
        "lng": "-82.32",
        "gtopo30": "",
        "zoom": "2",
        "lat": "34.866"
    },
    "markers": [
        {
            "tz": "America/New_York",
            "fcn": "airport",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "310",
            "id": "4580554",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85031",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "312",
            "discussionURL": "",
            "c": "AIRP",
            "lng": "-82.3509",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "GMU,Greenville Downtown Airport,KGMU",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4580554/greenville-downtown-airport.html",
            "population": "0",
            "wikipediaURL": "en.wikipedia.org/wiki/Greenville_Downtown_Airport",
            "admn4": "",
            "admn5": "",
            "name": "Greenville Downtown Airport",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "park",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "299",
            "id": "4572930",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86873",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "303",
            "discussionURL": "",
            "c": "PRK",
            "lng": "-82.33706",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4572930/butler-springs-park.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Butler Springs Park",
            "fc": "L"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.31249",
                "south": "34.84529",
                "north": "34.86328",
                "west": "-82.33441"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "308",
            "id": "4590207",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85428",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "321",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.32345",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4590207/orchard-park.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Orchard Park",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.31471",
                "south": "34.85946",
                "north": "34.87744",
                "west": "-82.33664"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "290",
            "id": "4593397",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86845",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "299",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.32567",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4593397/rogers-valley-heights.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Rogers Valley Heights",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.31888",
                "south": "34.85224",
                "north": "34.87022",
                "west": "-82.3408"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "318",
            "id": "4600306",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86123",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "334",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.32984",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4600306/watson-orchard.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Watson Orchard",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.28054",
                "south": "34.85029",
                "north": "34.86828",
                "west": "-82.30247"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "283",
            "id": "4601458",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85928",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "287",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.29151",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4601458/woodberry.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Woodberry",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.32221",
                "south": "34.8664",
                "north": "34.88439",
                "west": "-82.34414"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "271",
            "id": "4586853",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8754",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "302",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.33317",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4586853/mcswain-gardens.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "McSwain Gardens",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.30221",
                "south": "34.85446",
                "north": "34.87244",
                "west": "-82.32414"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "294",
            "id": "4587018",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86345",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "299",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.31317",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4587018/merrifield-park.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Merrifield Park",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.29166",
                "south": "34.85168",
                "north": "34.86967",
                "west": "-82.31358"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "290",
            "id": "4588494",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86067",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "295",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.30262",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4588494/mountain-brook.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Mountain Brook",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.27943",
                "south": "34.84446",
                "north": "34.86244",
                "west": "-82.30136"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "274",
            "id": "4572358",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85345",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "282",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.29039",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4572358/brookfield-east.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Brookfield East",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.28749",
                "south": "34.84779",
                "north": "34.86578",
                "west": "-82.30941"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "275",
            "id": "4572359",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85678",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "285",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.29845",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4572359/brookfield-west.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Brookfield West",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.29276",
                "south": "34.87057",
                "north": "34.88856",
                "west": "-82.31469"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "274",
            "id": "4576515",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87956",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "276",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.30373",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4576515/del-norte.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Del Norte",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.29276",
                "south": "34.86196",
                "north": "34.87994",
                "west": "-82.31469"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "294",
            "id": "4576588",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87095",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "302",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.30373",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4576588/devenger-place.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Devenger Place",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.2911",
                "south": "34.85779",
                "north": "34.87578",
                "west": "-82.31302"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "294",
            "id": "4579123",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86678",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "304",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.30206",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4579123/foxcroft.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Foxcroft",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.3061",
                "south": "34.86335",
                "north": "34.88133",
                "west": "-82.32803"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "293",
            "id": "4580411",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87234",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "305",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.31706",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4580411/green-fields.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Green Fields",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.32777",
                "south": "34.86835",
                "north": "34.88633",
                "west": "-82.34969"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "274",
            "id": "4581511",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87734",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "300",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.33873",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4581511/hermitage-hills.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hermitage Hills",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.3286",
                "south": "34.85501",
                "north": "34.873",
                "west": "-82.35053"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "335",
            "id": "4582471",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86401",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "335",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.33956",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4582471/hudson-acres.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hudson Acres",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.33054",
                "south": "34.86196",
                "north": "34.87994",
                "west": "-82.35247"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "299",
            "id": "4584365",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87095",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "305",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.34151",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4584365/lake-forest.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Lake Forest",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.3061",
                "south": "34.86723",
                "north": "34.88522",
                "west": "-82.32803"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "289",
            "id": "4597312",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87623",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "297",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.31706",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4597312/spring-forest.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Spring Forest",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.32499",
                "south": "34.86196",
                "north": "34.87994",
                "west": "-82.34691"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "299",
            "id": "4597313",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87095",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "305",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.33595",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4597313/spring-forest.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Spring Forest",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.31054",
                "south": "34.85779",
                "north": "34.87578",
                "west": "-82.33247"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "293",
            "id": "4597773",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86678",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "305",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.32151",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4597773/stratton-place.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Stratton Place",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.30138",
                "south": "34.86473",
                "north": "34.88272",
                "west": "-82.3233"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "305",
            "id": "4598408",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87373",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "309",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.31234",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4598408/terra-oaks.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Terra Oaks",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.33055",
                "south": "34.85779",
                "north": "34.87578",
                "west": "-82.35247"
            },
            "fcn": "populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "299",
            "id": "4598682",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86678",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "318",
            "discussionURL": "",
            "c": "PPL",
            "lng": "-82.34151",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4598682/timberlake.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Timberlake",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "fcn": "mountain",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "335",
            "id": "4050334",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85956",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "363",
            "discussionURL": "",
            "c": "MT",
            "lng": "-82.34067",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4050334/butler-hill.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Butler Hill",
            "fc": "T"
        },
        {
            "tz": "America/New_York",
            "bbox": {
                "east": "-82.34685",
                "south": "34.86208",
                "north": "34.86927",
                "west": "-82.35562"
            },
            "fcn": "section of populated place",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "304",
            "id": "4589421",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86567",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "316",
            "discussionURL": "",
            "c": "PPLX",
            "lng": "-82.35123",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4589421/north-gardens.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "North Gardens",
            "fc": "P"
        },
        {
            "tz": "America/New_York",
            "fcn": "road junction",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "4582929",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85428",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "330",
            "discussionURL": "",
            "c": "RDJCT",
            "lng": "-82.33512",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4582929/interchange-39.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Interchange 39",
            "fc": "R"
        },
        {
            "tz": "America/New_York",
            "fcn": "building(s)",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "294",
            "id": "7312542",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8554",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "300",
            "discussionURL": "",
            "c": "BLDG",
            "lng": "-82.3138",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/7312542/wade-hampton-fire-department-station-2.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Wade Hampton Fire Department Station 2",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "building(s)",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "289",
            "id": "7312544",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8789",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "292",
            "discussionURL": "",
            "c": "BLDG",
            "lng": "-82.3179",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/7312544/wade-hampton-fire-department-station-4.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Wade Hampton Fire Department Station 4",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hospital",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "308",
            "id": "8089327",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85152",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "309",
            "discussionURL": "",
            "c": "HSP",
            "lng": "-82.32346",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/8089327/saint-francis-eastside-medical-center.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Saint Francis Eastside Medical Center",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hospital",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "8089401",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85255",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "319",
            "discussionURL": "",
            "c": "HSP",
            "lng": "-82.32708",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/8089401/patewood-memorial-hospital.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Patewood Memorial Hospital",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hospital",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "8089404",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85461",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "318",
            "discussionURL": "",
            "c": "HSP",
            "lng": "-82.32513",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/8089404/greenville-endoscopy-center-at-patewood.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Greenville Endoscopy Center at Patewood",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hospital",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "308",
            "id": "8089411",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8553",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "322",
            "discussionURL": "",
            "c": "HSP",
            "lng": "-82.32348",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/8089411/greenville-hospital-system-outpatient-surgery-center-patewood.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Greenville Hospital System Outpatient Surgery Center Patewood",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hospital",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "8089412",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85682",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "330",
            "discussionURL": "",
            "c": "HSP",
            "lng": "-82.32736",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/8089412/upstate-surgery-center.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Upstate Surgery Center",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hospital",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "8089421",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8555",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "324",
            "discussionURL": "",
            "c": "HSP",
            "lng": "-82.32614",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/8089421/center-for-special-surgery.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Center for Special Surgery",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hospital",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "318",
            "id": "8089430",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86385",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "314",
            "discussionURL": "",
            "c": "HSP",
            "lng": "-82.33188",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/8089430/endoscopy-center-of-the-upstate.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Endoscopy Center of the Upstate",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "church",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "294",
            "id": "4590734",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85484",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "299",
            "discussionURL": "",
            "c": "CH",
            "lng": "-82.31428",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4590734/pelham-road-church.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Pelham Road Church",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "school",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "294",
            "id": "4590735",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85873",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "302",
            "discussionURL": "",
            "c": "SCH",
            "lng": "-82.31067",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4590735/pelham-road-elementary-school.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Pelham Road Elementary School",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "reservoir(s)",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "293",
            "id": "4591150",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87407",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "273",
            "discussionURL": "",
            "c": "RSV",
            "lng": "-82.32427",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4591150/pine-grove-lake.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Pine Grove Lake",
            "fc": "H"
        },
        {
            "tz": "America/New_York",
            "fcn": "church",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "289",
            "id": "4593156",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87651",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "295",
            "discussionURL": "",
            "c": "CH",
            "lng": "-82.3204",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4593156/rock-hill-church.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Rock Hill Church",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "church",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "278",
            "id": "4593793",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.88178",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "301",
            "discussionURL": "",
            "c": "CH",
            "lng": "-82.34984",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4593793/saint-francis-church.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Saint Francis Church",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "church",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "305",
            "id": "4593814",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87151",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "313",
            "discussionURL": "",
            "c": "CH",
            "lng": "-82.31206",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4593814/saint-giles-church.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Saint Giles Church",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "reservoir(s)",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "4601563",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85176",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "306",
            "discussionURL": "",
            "c": "RSV",
            "lng": "-82.34054",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4601563/woods-lake.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Woods Lake",
            "fc": "H"
        },
        {
            "tz": "America/New_York",
            "fcn": "church",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "327",
            "id": "4585912",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85651",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "337",
            "discussionURL": "",
            "c": "CH",
            "lng": "-82.34456",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4585912/lowndes-hill-church.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Lowndes Hill Church",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "school",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "293",
            "id": "4587452",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87234",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "304",
            "discussionURL": "",
            "c": "SCH",
            "lng": "-82.31873",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4587452/mitchell-road-christian-academy.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Mitchell Road Christian Academy",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "school",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "289",
            "id": "4587453",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87678",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "295",
            "discussionURL": "",
            "c": "SCH",
            "lng": "-82.31956",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4587453/mitchell-road-elementary-school.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Mitchell Road Elementary School",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "church",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "280",
            "id": "4571807",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.86484",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "297",
            "discussionURL": "",
            "c": "CH",
            "lng": "-82.29373",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4571807/boiling-springs-church.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Boiling Springs Church",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "church",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "289",
            "id": "4577328",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87678",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "292",
            "discussionURL": "",
            "c": "CH",
            "lng": "-82.32095",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4577328/east-north-street-church.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "East North Street Church",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "mall",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "4581335",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85151",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "317",
            "discussionURL": "",
            "c": "MALL",
            "lng": "-82.33179",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4581335/haywood-mall-shopping-center.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Haywood Mall Shopping Center",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "reservoir(s)",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "307",
            "id": "4584362",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87178",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "307",
            "discussionURL": "",
            "c": "RSV",
            "lng": "-82.34984",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4584362/lake-fairfield.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Lake Fairfield",
            "fc": "H"
        },
        {
            "tz": "America/New_York",
            "fcn": "dam",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "307",
            "id": "4584363",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87178",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "307",
            "discussionURL": "",
            "c": "DAM",
            "lng": "-82.34984",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4584363/lake-fairfield-dam-d-2886.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Lake Fairfield Dam D-2886",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "school",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "278",
            "id": "4584367",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.88151",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "303",
            "discussionURL": "",
            "c": "SCH",
            "lng": "-82.34373",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4584367/lake-forest-elementary-school.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Lake Forest Elementary School",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "reservoir(s)",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "276",
            "id": "4599615",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87178",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "279",
            "discussionURL": "",
            "c": "RSV",
            "lng": "-82.29317",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4599615/w-r-cely-pond.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "W R Cely Pond",
            "fc": "H"
        },
        {
            "tz": "America/New_York",
            "fcn": "dam",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "276",
            "id": "4599616",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.87178",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "elevation": "279",
            "discussionURL": "",
            "c": "DAM",
            "lng": "-82.29317",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/4599616/w-r-cely-pond-dam-d-2892.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "W R Cely Pond Dam D-2892",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "6474005",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8554",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3306",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/6474005/courtyard-by-marriott-greenville-haywood.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Courtyard by Marriott Greenville (Haywood)",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "6475508",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8568",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3364",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/6475508/amerisuites-greenville.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Amerisuites - Greenville",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "6483894",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8569",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3365",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/6483894/hilton-greenville.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hilton Greenville",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "6473098",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8573",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3373",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/6473098/la-quinta-inn-and-suites-greenville-haywood.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "La Quinta Inn and Suites Greenville Haywood",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "6461955",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.856",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3318",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/6461955/econo-lodge-haywood.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Econo Lodge Haywood",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "6488492",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8556",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3318",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/6488492/hawthorn-suites.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hawthorn Suites",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "9855683",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8561",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3317",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/9855683/clarion-inn-%26-suites-spartanburg.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Clarion Inn & Suites Spartanburg",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "9855694",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85292",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33631",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/9855694/hampton-inn-greenville-haywood.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hampton Inn Greenville-Haywood",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "9855713",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85551",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3307",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/9855713/courtyard-greenville-haywood-mall.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Courtyard Greenville Haywood Mall",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "9863576",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85186",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3377",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/9863576/hampton-innhaywood-rd-greenville.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hampton Innhaywood Rd Greenville",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "10339114",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85609",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33167",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10339114/clarion-inn-and-suites.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Clarion Inn and Suites",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "10285952",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8568",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3366",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10285952/hilton-and-towers.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hilton and Towers",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "10284689",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85124",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33952",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10284689/extended-stay-america-greenville-haywood-mall.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Extended Stay America Greenville Haywood Mall",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "10247645",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8537",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3367",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10247645/hampton-inn-greenville-haywood-road.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hampton Inn Greenville Haywood Road",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "10344344",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85632",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33683",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10344344/hilton-greenville-y-torres.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hilton Greenville Y Torres",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "10344883",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85291",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33645",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10344883/hampton-inn-greenville-i-385-haywood-mall.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hampton Inn Greenville I 385 Haywood Mall",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "9949034",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85739",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33728",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/9949034/la-quinta-haywood-road.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "La Quinta Haywood Road",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "9851094",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85625",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33227",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/9851094/clarion-inn-%26-suites-greenville.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Clarion Inn & Suites Greenville",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "9854330",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85632",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3369",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/9854330/hilton-greenville-%26-towers.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hilton Greenville & Towers",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "10105929",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.853",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3361",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10105929/hampton-inn-haywood-rd-greenville-sc.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hampton Inn-Haywood Rd Greenville Sc",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "10062705",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85625",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33227",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10062705/clarion-inn-%26-suites-haywood-mall-area.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Clarion Inn & Suites Haywood Mall Area",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "329",
            "id": "10174883",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85557",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33169",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10174883/hawthorn-suites-by-wyndham-greenville.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Hawthorn Suites By Wyndham Greenville",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "10175812",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.85291",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.33635",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/10175812/baymont-inn-%26-suites-greenville.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Baymont Inn & Suites Greenville",
            "fc": "S"
        },
        {
            "tz": "America/New_York",
            "fcn": "hotel",
            "admId2": "4580549",
            "admId1": "4597040",
            "admc5": "",
            "gtopo30": "324",
            "id": "6517672",
            "tag": "",
            "admc3": "",
            "admc4": "",
            "admc1": "SC",
            "lat": "34.8511",
            "admc2": "045",
            "cId": "6252001",
            "cc": "US",
            "discussionURL": "",
            "c": "HTL",
            "lng": "-82.3395",
            "admn2": "Greenville County",
            "admn3": "",
            "altname": "",
            "admn1": "South Carolina",
            "cn": "United States",
            "url": "http://www.geonames.org/6517672/studioplus-greenville-haywood.html",
            "population": "0",
            "wikipediaURL": "",
            "admn4": "",
            "admn5": "",
            "name": "Studioplus Greenville-Haywood",
            "fc": "S"
        }]
}];