export = [
	{ es: "carnitas", en: "little meats" },
	{ es: "cúerito", en: "pig skin" },
	{ es: "lengua de vaca", en: "cow tongue" },
	{ es: "queso", en: "cheese" },
	{ es: "frijoles", en: "red beans" },
	{ es: "chicharrón", en: "pork rind" },
	{ es: "revueltas", en: "mixture" },
	{ es: "pollo", en: "chicken" },
	{ es: "res", en: "beef" },
	{ es: "texana", en: "texas style" },
	{ es: "camarón", en: "shrimp" },
	{ es: "piña", en: "pineapple" },
	{ es: "horchata", en: "almond juice" },
	{ es: "bebidas", en: "drinks" },
	{ es: "tepache", en: "pinapple mixed" },
	{ es: "caldo de pollo", en: "chicken soup" },
	{ es: "fajita de res texana", en: "beef fajita" },
	{ es: "caldo de siete mares", en: "seven seas soup" },
	{ es: "fajita de pollo", en: "chicken fajita" },
	{ es: "enchiladas verdes", en: "enchilada" },
	{ es: "enchiladas rojas y verdes", en: "enchilada" },
	{ es: "caldo de cangrejo", en: "" },
	{ es: "costilla asada de res", en: "grilled beef ribs" },
	{ es: "suadero", en: "brisket" },
	{ es: "cabeza", en: "cow head" },
	{ es: "flor de calabaza", en: "squash blossom" },
	{ es: "huitlacoche", en: "corn smut" },
	{ es: "pollo asado", en: "grilled chicken" },
	{ es: "milanesas", en: "breaded cutlet" },
	{ es: "carne asada", en: "beef steak" },
	{ es: "caldo de res", en: "beef soup" },
	{ es: "caldo de camarón", en: "shrimp soup" },
	{ es: "el caldo de menudo", en: "soup of the day" }
].map(v => ({ es: v.es, en: v.en }));
