import { forceGender } from "../quizlet/fun";

export = [
	{ es: "gato", en: "cat" },
	{ es: "perro", en: "dog" },
	{ es: "árbol", en: "tree" },
	{ es: "cielo", en: "heaven" },
	{ es: "tierra", en: "earth" },
	{ es: "cruz", en: "cross" },
	{ es: "cuerpo", en: "body" },
	{ es: "sepulcro", en: "grave" },
	{ es: "estruendo", en: "roar" },
	{ es: "rostro", en: "face" },
	{ es: "Dios", en: "God" },
	{ es: "amanecer", en: "dawn" },
	{ es: "muerte", en: "death" },
	{ es: "asada", en: "grilled" },
	{ es: "carnitas", en: "little meats" },
	{ es: "cúerito", en: "pig skin" },
	{ es: "lengua de vaca", en: "cow tongue" },
	{ es: "queso", en: "cheese" },
	{ es: "frijoles", en: "red beans" },
	{ es: "chicharrón", en: "pork rind" },
	{ es: "revueltas", en: "mixture" },
	{ es: "pollo", en: "chicken" },
	{ es: "res", en: "beef" },
	{ es: "tejana", en: "texas style" },
	{ es: "camarón", en: "shrimp" },
	{ es: "piña", en: "pineapple" },
	{ es: "horchata", en: "almond juice" },
	{ es: "bebidas", en: "drinks" },
	{ es: "tepache", en: "pinapple mixed" },
	{ es: "caldo de pollo", en: "chicken soup" },
	{ es: "fajita de res texana", en: "beef fajita" },
	{ es: "caldo siete mares", en: "seven seas soup" },
	{ es: "fajita de pollo", en: "chicken fajita" },
	{ es: "enchiladas verdes", en: "enchilada" },
	{ es: "enchiladas rojas y verdes", en: "enchilada" },
	{ es: "caldo de cangrejo", en: "" },
	{ es: "costilla asada de res", en: "" },
	{ es: "guacho mango", en: "" },
	{ es: "suadero", en: "brisket" },
	{ es: "cabeza", en: "cow head" },
	{ es: "camarones", en: "" },
	{ es: "flor de calabaza", en: "squash blossom" },
	{ es: "huitlacoche", en: "corn smut" },
	{ es: "pollo asado", en: "grilled chicken" },
	{ es: "milanesas", en: "breaded cutlet" },
	{ es: "carne asada", en: "beef steak" },
	{ es: "caldo de res", en: "beef soup" },
	{ es: "caldo de camarón", en: "shrimp soup" },
	{ es: "el caldo de menudo", en: "soup of the day" }
].map(v => ({ es: forceGender(v.es), en: "the " + v.en }));
